    @startuml
    left to right direction

    actor Visiteur as "user"
    actor Blogueur as "Bloger"

    rectangle "Blog" {
        usecase "View Blogs" as UC_ConsulterArticles
        usecase "CRUD Categories" as UC_Categorie
        usecase "CRUD Blog" as UC_Article  
        usecase "Authentification" as Auth
    }
    Blogueur -- UC_Article
    Blogueur -- UC_Categorie
    Visiteur -- UC_ConsulterArticles
    UC_Categorie .-> Auth : "include"
    UC_Article .-> Auth : "include"
    @enduml