    @startuml
    left to right direction

    actor Visiteur
    actor Blogueur

    rectangle "Blog" {
        usecase "Consulter article" as UC_ConsulterArticles
        usecase "CRUD Catégorie" as UC_Categorie
        usecase "CRUD Article" as UC_Article  
        usecase "Authentification" as Auth
    }
    Blogueur -- UC_Article
    Blogueur -- UC_Categorie
    Visiteur -- UC_ConsulterArticles
    UC_Categorie .-> Auth : "include"
    UC_Article .-> Auth : "include"
    @enduml